engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Design/TooManyMethods:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
ratings:
  paths:
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
  - tests/*
