engines:
  phpcodesniffer:
    enabled: true
    checks:
      Generic Files LineEndings InvalidEOLChar:
        enabled: false
      PSR1 Classes ClassDeclaration MissingNamespace:
        enabled: false
  phpmd:
    enabled: true
    checks:
      Design/TooManyMethods:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
ratings:
  paths:
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
  - "tests/*"
